@HostAddress = http://localhost:5162

GET {{HostAddress}}/api/customers
Accept: application/json

###

POST {{HostAddress}}/api/customers
Content-Type: application/json

{
  "fullName": "Saron",
  "phone": "0912345678",
  "email": "saron@example.com"
}
###

### Get all services
GET {{HostAddress}}/api/services
Accept: application/json

###

### Create a service
POST {{HostAddress}}/api/services
Content-Type: application/json

{
  "name": "Haircut",
  "price": 300,
  "durationMinutes": 45,
  "category": "Hair"
}
###

### Get all staff
GET {{HostAddress}}/api/staff
Accept: application/json

###

### Create staff
POST {{HostAddress}}/api/staff
Content-Type: application/json

{
  "fullName": "Meron",
  "role": "Hair Stylist",
  "phone": "0922334455"
}

###

### Get appointments
GET {{HostAddress}}/api/appointments
Accept: application/json

###

### Create appointment
###
POST {{HostAddress}}/api/appointments
Content-Type: application/json

{
  "customerId": 1,
  "staffId": 1,
  "appointmentDate": "2026-08-20T10:00:00Z",
  "status": "Scheduled",
  "notes": "First appointment"
}
###

### Get appointment services
GET {{HostAddress}}/api/appointmentservices
Accept: application/json

###

### Add Haircut to Saron's appointment
POST {{HostAddress}}/api/appointmentservices
Content-Type: application/json

{
  "appointmentId": 1,
  "serviceId": 2,
  "price": 500
}

### Create Service
POST {{HostAddress}}/api/services
Content-Type: application/json

{
  "name": "Haircut",
  "price": 500,
  "durationMinutes": 60,
  "category": "Hair"
}
### Create Payment
POST {{HostAddress}}/api/payments
Content-Type: application/json

{
  "appointmentId": 1,
  "amount": 800,
  "paymentDate": "2026-08-20T11:00:00Z",
  "method": "Cash",
  "status": "Paid"
}
### Get Payments
GET {{HostAddress}}/api/payments
Accept: application/json
### Update Payment
PUT {{HostAddress}}/api/payments/1
Content-Type: application/json

{
  "id": 1,
  "appointmentId": 1,
  "amount": 900,
  "paymentDate": "2026-08-20T11:00:00Z",
  "method": "Cash",
  "status": "Paid"
}

###

### Delete Payment
DELETE {{HostAddress}}/api/payments/1